### ISSUE TITLE
dunfell release

### ISSUE THREAD

**Issue by floion** [compulab-yokneam/meta-bsp-imx8mm#10]
Hi, do you have a dunfell compatible release of your layer?

Thanks!

**Comment by floion** [comment]
One other thing: we'd need dunfell support for the `iot-gate-imx8` machine

**Comment by mwsoverdick** [comment]
I don't know if they have a Dunfell compatible release yet, I believe that they just released Zeus sometime in September 2020. 

For what it's worth, my company would also love a Dunfell release since it is the only one so far with long term support. Hopefully we get a response soon, thanks for posting this.

**Comment by vraevsky** [comment]
Hello All,

Dunfell support is here:
https://github.com/compulab-yokneam/compulab-fslc-bsp

BR,
Val

**Comment by mwsoverdick** [comment]
Thank you Val!

I do not understand the difference between `meta-bsp-imx8mm` and `compulab-fslc-bsp`. What is the intended use case of each repository? I just want to be sure in case one of these is not stable for production code.

Best,
Mitchell
